### ISSUE TITLE
OneAdapter's Credit

### ISSUE THREAD

**Issue by idanatz** [trieulh-ict/SimpleGenericAdapter#4]
Hi, OneAdapter's main contributor.

It would be nice to be more precise, it's not "Inspired by OneAdapter" it's more based on our adapter.
The internal logic, module structure, and even extension functions are the same.
Please add link reference to our Github repo.

https://github.com/ironSource/OneAdapter

Good luck.

**Comment by trieulh-ict** [comment]
@idanatz Sorry for those unclear words. I updated README to link to your library. 
Thanks so much and have a good day.
